/* Calandria desktop shell — Electron main process.
 *
 * SPIKE CODE. See ./README.md and docs/DESKTOP_APP.md.
 *
 * Intentionally thin. Everything that can be tested without a display lives in
 * supervisor.js; this file is window + menu + lifecycle, and it holds exactly
 * one piece of policy: the renderer is a hardened browser tab pointed at
 * 127.0.0.1, not a privileged page. No preload, no nodeIntegration, no IPC —
 * the app already talks to its server over HTTP/SSE/WS and gains nothing from
 * a bridge, while a bridge would hand any XSS in the transcript renderer the
 * whole Node API.
 */
"use strict";

const { app, BrowserWindow, Menu, Notification, Tray, nativeImage, shell, dialog, session } = require("electron");
const path = require("node:path");
const { Supervisor, preferredPorts } = require("./supervisor");
const {
  AppEvents,
  NeedsYou,
  overlayIconName,
  selectedTaskFromUrl,
  shouldNotify,
  trayTooltip,
} = require("./notifier");
const { confirmTrayResidency } = require("./tray-residency");

// Where the server payload lives — the thing supervisor.js runs `node server.js`
// out of. Packaged, it is extraResources sitting NEXT TO the asar, not inside
// it: it holds native addons that dlopen from a real path and it is spawned as
// a child process, neither of which can see into an archive (staged by
// scripts/build-payload.js, mapped to resources/app-payload by the
// electron-builder config in package.json). Unpackaged, it is the checkout this
// file sits in, so `cd desktop && npm start` against a repo stays the developer
// flow. CALANDRIA_REPO_ROOT overrides both, which is how a packaged binary gets
// pointed at a working tree.
const REPO_ROOT =
  process.env.CALANDRIA_REPO_ROOT ||
  (app.isPackaged ? path.join(process.resourcesPath, "app-payload") : path.resolve(__dirname, ".."));
const LOADING_PAGE = `file://${path.join(__dirname, "loading.html")}`;
// Committed PNGs, regenerated by scripts/make-assets.py. Inside the asar when
// packaged, which is fine for both consumers: Tray and nativeImage read through
// Electron's own fs shim.
const ASSETS = path.join(__dirname, "assets");

let win = null;
let supervisor = null;
let appUrl = null;
let quitting = false;
// A fatal failure is reported once, by whichever path notices it first. A
// sidecar that dies DURING boot trips both of them: the Supervisor's `onExit`
// fires, and `supervisor.start()` then rejects with that same child's reason —
// so the user gets the specific dialog and a second, vaguer one stacked on it.
// In production the first `app.exit(1)` usually tears the process down before
// the second is drawn, which is what makes this a race rather than a constant;
// the interlock makes the outcome the same on a loaded machine as on an idle
// one. Same shape as `quitting` above, and checked alongside it.
let failed = false;
let tray = null;
// Whether that icon is actually IN a status area — which is a different fact
// from `tray` being an object, and the one the close handler needs. See
// tray-residency.js, and `refreshTrayResidency()` below for the rule that moves
// it. False until the session says otherwise, so nothing promises a tray it has
// not seen.
let trayHosted = false;
// Has the session ever answered? Only so the first answer is logged even when
// it agrees with the pessimistic default — a launch that found no status area
// has to say so.
let trayResidencyKnown = false;
// One close decision at a time: the handler now answers asynchronously, and a
// second X while the first is still asking would ask again rather than wait.
let closePending = false;
let events = null;
let needsYou = null;
let needsYouCount = 0;
// Live toasts by payload id, so a second notification about the same task
// replaces the first instead of stacking. The browser channel gets this from
// `Notification.tag`; Electron's main-process Notification has no tag, so the
// collapse is done by hand against the same id the server minted.
const liveToasts = new Map();

// One shell per machine. This mirrors, at the UI layer, the single-process rule
// lib/db-lock.mjs enforces at the database layer: a second launch would spawn a
// second server, lose the lock race, and exit(1) with an error the user reads as
// a crash. Focusing the existing window is what they meant anyway.
if (!app.requestSingleInstanceLock()) {
  app.exit(0);
} else {
  app.on("second-instance", () => showWindow());
  main();
}

function main() {
  app.on("window-all-closed", () => {
    // Normally unreachable: the close handler below hides the window rather
    // than destroying it, on every platform (see "Close vs quit" in
    // docs/DESKTOP_APP.md §5.1). The one way here is a close that arrives
    // BEFORE boot() finished — that handler lets those through, since there is
    // no server to keep alive and no confirmed tray to be present in yet — and
    // there, quitting is exactly what the user asked for. Gated on the same
    // confirmed tray the close handler uses, rather than on the platform, so a
    // hide can never be mistaken for a quit.
    if (!trayHosted) app.quit();
  });

  app.on("activate", () => showWindow());

  // Quit is the only place in-flight turns can be drained: supervisor.stop()
  // POSTs /api/instance/drain and waits for the turns to settle before it
  // stops the sidecars. Hold the quit open for exactly as long as that takes.
  app.on("before-quit", async (event) => {
    if (quitting || !supervisor) return;
    quitting = true;
    event.preventDefault();
    // Nothing that arrives from here on has anywhere to go: the badge is about
    // to disappear with the process, and a toast raised during a shutdown is
    // one the user cannot act on.
    events?.stop();
    showDraining();
    try {
      await supervisor.stop();
    } finally {
      // Explicitly, before exit: a tray icon whose process is gone is left
      // behind as a dead slot by several Linux status-bar implementations.
      tray?.destroy();
      tray = null;
      trayHosted = false;
      trayResidencyKnown = false;
      app.exit(0);
    }
  });

  app.whenReady().then(async () => {
    Menu.setApplicationMenu(buildMenu());
    announceShell();
    hardenSession();
    createWindow();
    await boot();
  });
}

function createWindow() {
  win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 720,
    minHeight: 480,
    backgroundColor: "#0b0d10",
    show: true,
    title: "Calandria",
    // A dark, borderless-ish title bar on macOS matches the app's own titlebar;
    // on Windows/Linux the native frame stays, since the app has no custom
    // window controls of its own to replace it with.
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      spellcheck: true,
    },
  });

  // The boot screen only while there is nothing better: a window recreated
  // after its predecessor was destroyed (macOS, dock click) must land on the
  // app, not on a spinner for a server that came up minutes ago.
  win.loadURL(appUrl || LOADING_PAGE);

  // Anything that isn't our own loopback origin opens in the user's real
  // browser: GitHub PR links, docs, a task's exposed service. A new
  // BrowserWindow for those would be a browser we then have to maintain.
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (isAppUrl(url)) return { action: "allow" };
    shell.openExternal(url);
    return { action: "deny" };
  });
  win.webContents.on("will-navigate", (event, url) => {
    if (isAppUrl(url) || url.startsWith("file://")) return;
    event.preventDefault();
    shell.openExternal(url);
  });

  // CLOSE VS QUIT — one rule on all three platforms: the X button (and Cmd+W)
  // HIDES the window, and quitting is something you ask for by name. The
  // reasoning, and what changed to allow it, is in docs/DESKTOP_APP.md §5.1.
  //
  // The short version: closing used to quit on Windows and Linux because
  // "leaving turns running invisibly with no window is worse than stopping
  // them" — and that was right while the shell had no way to be present
  // without a window. It now has one. The tray icon is on screen, it carries
  // the "N need you" count, and Show is one click away; a hidden Calandria is
  // no more invisible than a minimised one. Against that, close-to-quit on a
  // window whose whole job is supervising long agent turns means every
  // absent-minded X kills work in flight — and the drain that protects it
  // (which is real, and which desktop/e2e/03-quit-drain.spec.ts pins) only
  // makes the shutdown slower, not less unwanted.
  //
  // Hiding rather than destroying is also what keeps the renderer's state: the
  // SPA's open transcript, scroll position and SSE streams survive, so
  // reopening is instant instead of a cold reload. That is why macOS hides too
  // even though its convention would permit a real close — `activate` then
  // shows the same window instead of building a new one.
  //
  // Three escapes, all deliberate, and the first is the load-bearing one: this
  // hides only while a status area is ACTUALLY DRAWING the tray icon. The gate
  // used to be `new Tray()` not throwing, which is a much weaker thing and is
  // not true of the case it was written for: on Linux the constructor succeeds
  // on a session with no status-notifier host, so the window hid into nowhere
  // and the "open it again from the tray icon" toast named an icon that did not
  // exist (tray-residency.js carries the measurement). Refusing to hide
  // somewhere the user cannot get the app back from is the old rationale, still
  // correct — it just needs the session's answer rather than Electron's. A
  // close BEFORE boot() finished is let through for the same reason (no server
  // to keep alive, no tray yet), and `window-all-closed` turns it into a quit.
  // And a close DURING the drain is let through as well — by then the user has seen
  // the drain state and asked twice, and `supervisor.stop()` is bounded anyway,
  // so the wait cannot outlive the grace.
  win.on("close", (event) => {
    if (quitting || !supervisor) return;
    // Always prevented here and resolved in `decideClose()`: the answer is a
    // question for the session bus, which cannot be asked synchronously, and a
    // close that is allowed through cannot be taken back.
    event.preventDefault();
    if (closePending) return;
    closePending = true;
    void decideClose().finally(() => {
      closePending = false;
    });
  });

  win.on("closed", () => {
    win = null;
  });
}

function isAppUrl(url) {
  if (!appUrl) return false;
  try {
    const u = new URL(url);
    return u.origin === new URL(appUrl).origin;
  } catch {
    return false;
  }
}

function announceShell() {
  // The one thing the page is told about its container, and it is told in the
  // user agent because that is the only channel that is already per-CLIENT: the
  // same server can be open in this window and in an ordinary browser tab at
  // the same moment, so an env var on the sidecars or a flag in the per-instance
  // `window.__FEATURES` bundle would answer one of them with the other's truth.
  //
  // What it buys, today, is one sentence: Settings → Notifications reads
  // `Notification.permission`, which hardenSession() below makes "denied", and
  // saying "you've blocked notifications for this site" to somebody who is
  // getting OS toasts from us the whole time sends them looking for a browser
  // setting this window does not have. app/shell/useNotifications.ts matches
  // this token (isDesktopShell) and reports "handled by the desktop app".
  //
  // Appended rather than replacing, so the Chrome/Electron versions the app may
  // reasonably branch on survive; must be set before the first load.
  app.userAgentFallback = `${app.userAgentFallback} Calandria-Desktop/${app.getVersion()}`;
}

function hardenSession() {
  // Default-deny, so a future dependency can't quietly acquire the camera.
  //
  // `notifications` is denied HERE and raised from the main process instead —
  // the one permission this handler used to grant. Both channels read the same
  // server-composed payload off /api/events, so granting it would give the user
  // two toasts for every event: Chromium's, from app/shell/useNotifications.ts,
  // and the shell's. The main process wins because it is the half that can
  // still fire with the window hidden to the tray or destroyed, can raise the
  // window and select the task on click, and owns the dock/taskbar badge that
  // has to agree with what it just said. The renderer's channel stands down
  // cleanly on its own: `notificationPermission()` returns something that isn't
  // `granted` and the hook returns before constructing anything. It returns
  // `desktop_shell`, not the raw `denied`, off the token announceShell() sets
  // above — so Settings can say the desktop app owns this rather than telling
  // the user they blocked a site setting this window cannot open.
  session.defaultSession.setPermissionRequestHandler((_wc, permission, callback) => {
    callback(permission === "clipboard-sanitized-write");
  });
  // The request handler is NOT enough to switch the page's channel off, and
  // this is the half that actually does it. `useNotifications.ts` reads
  // `Notification.permission` — a permission CHECK, which Electron answers with
  // a hardcoded "granted" when no check handler is set, whatever the request
  // handler would have said. So the hook would have sailed past its own guard
  // and shown the duplicate toast without ever asking. Only notifications are
  // named here: every other check keeps Electron's default answer, so this
  // adds one denial rather than quietly tightening a surface the request
  // handler above is the policy for.
  session.defaultSession.setPermissionCheckHandler((_wc, permission) => permission !== "notifications");
}

async function boot() {
  supervisor = new Supervisor({
    repoRoot: REPO_ROOT,
    // PORT/PTY_PORT are documented as env the shell understands, so read them
    // here — the Supervisor's own 3000/3001 are the fallback, not the policy.
    // Still preferences: a busy one is stepped past (see pickPorts).
    ...preferredPorts(process.env),
    resourcesPath: app.isPackaged ? process.resourcesPath : null,
    onLog: (line) => {
      // Two consumers: the terminal a developer launched us from, and the
      // loading screen's off-screen `#log`. The boot screen shows a spinner
      // rather than these lines — a scrolling wall of sidecar output is not
      // what someone waiting for the window wants to read — but they are still
      // pushed across, because that element is the only place the supervisor's
      // FIRST lines survive: Electron stdout capture starts after launch has
      // resolved, so desktop/e2e reads them back off the page instead.
      console.log(line);
      // executeJavaScript rather than IPC: the boot screen is the only consumer
      // and adding a preload for it would mean shipping a bridge into every
      // page the window later loads, including the app itself.
      //
      // The write is done HERE rather than by calling a helper the boot screen
      // defines, because loading.html's CSP is `default-src 'none'` and that
      // blocks its own inline <script> — so a `window.__log` defined in the page
      // never exists, and the `&&` guard this used to have made that failure
      // completely silent (the boot screen simply stayed blank for every launch
      // there has ever been; found by desktop/e2e/01-shell.spec.ts). A
      // main-process evaluation is not subject to the page's CSP, so pushing the
      // DOM write across keeps the strict policy AND makes the log show up.
      // Only while the boot screen is the page: once appUrl is set the window is
      // on the app, which has no #log and no interest in being evaluated into on
      // every line the sidecars print for the rest of the session.
      if (appUrl) return;
      const write = `(() => { const el = document.getElementById("log"); if (!el) return; el.textContent += ${JSON.stringify(line + "\n")}; el.scrollTop = el.scrollHeight; })()`;
      win?.webContents.executeJavaScript(write).catch(() => {});
    },
    onExit: ({ name, code, dbLockHeld }) => {
      if (quitting || failed) return;
      failed = true;
      // A sidecar dying while the app is up is not recoverable in place: the
      // renderer's SSE streams are already broken and the db lock may be gone.
      const detail = dbLockHeld
        ? "Another Calandria instance is already running against this database.\n\nQuit that one first, or open it in your browser."
        : `The ${name} process exited unexpectedly (code ${code}).\n\n${supervisor.recentLog(15)}`;
      dialog.showErrorBox("Calandria stopped", detail);
      app.exit(1);
    },
  });

  try {
    const { url } = await supervisor.start();
    appUrl = url;
    await win?.loadURL(url);
    win?.setTitle("Calandria");
    // After the app is up, not before: the tray's "Open in browser" needs a
    // URL, and the event stream needs a server to subscribe to.
    createTray();
    startEvents();
  } catch (err) {
    // `onExit` gets first claim when the failure was a sidecar dying, because
    // it knows WHICH one and whether the database was already held; this path
    // only has the rejection `start()` re-raised from it. Nothing left to do —
    // that path has already shown its dialog and asked for the exit.
    if (failed) return;
    failed = true;
    dialog.showErrorBox("Calandria could not start", `${err?.message || err}\n\n${supervisor?.recentLog(20) || ""}`);
    app.exit(1);
  }
}

/**
 * What quitting looks like while `supervisor.stop()` waits for the turns.
 *
 * Two signals because they answer to two places. The TITLE is what a window
 * manager shows, and on macOS it is the only one that matters — the window
 * stays and the user is looking at the dock. The OVERLAY is on the page, which
 * is where the eyes are on every platform, and it is also the only cue on a
 * desktop that draws no title bar at all. The page underneath is a live app
 * whose server is being shut down out from under it, so leaving it alone would
 * mean the last thing the user sees is a UI going wrong rather than one being
 * put away.
 *
 * Written from the main process, like the boot log and for the same reason:
 * the app serves its own CSP and a main-process evaluation is not subject to
 * it, so nothing here depends on the page cooperating. Best-effort throughout —
 * a window mid-navigation, or already gone, must not hold up the quit.
 */
function showDraining() {
  // Quit can now be asked for from the tray with the window hidden, so put it
  // back on screen first — otherwise the two signals below are written to
  // something nobody can see and the shutdown looks like a hang. Deliberately
  // NOT showWindow(): that builds a window when there isn't one, and a shell
  // that opens a fresh window on its way out is worse than a quiet exit.
  if (win && !win.isDestroyed()) {
    if (win.isMinimized()) win.restore();
    win.show();
  }
  win?.setTitle("Calandria — finishing in-flight turns…");
  win?.webContents.executeJavaScript(DRAIN_OVERLAY).catch(() => {});
}

const DRAIN_OVERLAY = `(() => {
  if (document.getElementById("calandria-draining")) return;
  const el = document.createElement("div");
  el.id = "calandria-draining";
  el.setAttribute("role", "status");
  el.style.cssText = [
    "position:fixed", "inset:0", "z-index:2147483647",
    "display:flex", "flex-direction:column", "align-items:center", "justify-content:center", "gap:10px",
    "background:rgba(11,13,16,.92)", "color:#e6e8eb", "-webkit-backdrop-filter:blur(2px)", "backdrop-filter:blur(2px)",
    'font:14px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
  ].join(";");
  const h = document.createElement("div");
  h.style.cssText = "font-size:16px;font-weight:600;letter-spacing:.2px";
  h.textContent = "Finishing in-flight turns…";
  const sub = document.createElement("div");
  sub.style.cssText = "color:#8b939c;font-size:12.5px";
  sub.textContent = "Calandria is settling running sessions before it stops. This window closes on its own.";
  el.append(h, sub);
  document.body.appendChild(el);
})()`;

/**
 * Put the window in front, from wherever it currently is — hidden to the tray,
 * minimised, behind the editor, or (macOS, after a real destroy) not there at
 * all. Every "come back" path goes through here: the tray's Show, a tray click,
 * `activate`, a second launch, and a notification click.
 */
function showWindow() {
  if (!win || win.isDestroyed()) {
    createWindow();
    return;
  }
  if (win.isMinimized()) win.restore();
  win.show();
  win.focus();
}

/**
 * Hide, or quit — decided by asking the session whether the tray icon is really
 * there, not by trusting that it was there at boot.
 *
 * Re-asked on every close ON PURPOSE, because the way this shell loses a window
 * is a status-notifier host that goes away MID-SESSION: Electron offers no
 * callback for it, so the only cheap moment to notice is the moment the answer
 * decides something. That is also why there is no `NameOwnerChanged`
 * subscription here — it would mean a long-lived `gdbus monitor` child for a
 * fact nothing consults in between.
 *
 * Budgeted at 1.5 s and retried inside that, so a panel that is restarting is
 * waited through rather than read as gone. A probe that cannot ANSWER leaves
 * the last answer standing (see `refreshTrayResidency`), so a machine with no
 * D-Bus CLI keeps whatever boot established rather than flipping on a timeout.
 */
async function decideClose() {
  const hosted = await refreshTrayResidency(1500);
  // The quit path may have started while we were asking — `before-quit` shows
  // the window again for the drain, so hiding it now would undo that.
  if (quitting) return;
  if (!hosted) {
    // Nowhere to hide into, so closing means quitting, and `app.quit()` is what
    // keeps the drain (and the on-screen wait for it) in the chain.
    app.quit();
    return;
  }
  if (!win || win.isDestroyed()) return;
  win.hide();
  announceTrayResidency();
}

/**
 * Re-read whether the tray icon is in a status area, and report the current
 * belief.
 *
 * ONE RULE, and it is the whole reason this is not a boolean assignment:
 * `trayHosted` moves only when the session gives an ANSWER. A probe that could
 * not run — no `gdbus`, no `dbus-send`, a timed-out call — is not evidence that
 * a working tray disappeared, and treating it as one would turn every X on a
 * healthy desktop into a quit.
 */
async function refreshTrayResidency(timeoutMs) {
  if (!tray) return false;
  const verdict = await confirmTrayResidency({ pid: process.pid, timeoutMs });
  if (verdict.hosted === null) {
    console.log(
      `[shell] could not confirm the tray icon (${verdict.reason}) — keeping the last answer: ` +
        `${trayHosted ? "hosted" : "not hosted"}`,
    );
    return trayHosted;
  }
  // Logged on the first answer and on every change after it, never on a repeat:
  // the first is what a launch needs to state (and what the e2e suite branches
  // on, since the two close behaviours are both correct and only the session
  // says which), the rest are the mid-session flips this exists to catch.
  if (!trayResidencyKnown || verdict.hosted !== trayHosted) {
    console.log(
      verdict.hosted
        ? `[shell] tray icon confirmed in the status area (${verdict.reason})`
        : `[shell] tray icon is not in any status area (${verdict.reason}) — closing the window will quit`,
    );
  }
  trayResidencyKnown = true;
  trayHosted = verdict.hosted;
  return trayHosted;
}

// Hiding a window is the one action here with no visible result, and on
// Windows and Linux it is also a CHANGE from what this shell used to do (the X
// used to quit). Say so once per launch, through the same channel everything
// else here uses, so the first close doesn't read as a crash. Once only: a
// reminder every time would be the nag that makes people avoid the button.
let trayResidencyAnnounced = false;

function announceTrayResidency() {
  // `trayHosted`, never `tray`: this is the one message that tells the user
  // where the window went, so raising it on a session with no icon is worse
  // than saying nothing at all. `decideClose()` has already re-confirmed by the
  // time this runs, and only calls it on the hide branch.
  if (trayResidencyAnnounced || !trayHosted || !Notification.isSupported()) return;
  trayResidencyAnnounced = true;
  new Notification({
    title: "Calandria is still running",
    body: "Turns keep going in the background. Open it again from the tray icon, or quit from its menu.",
  }).show();
}

/**
 * The tray icon: the shell's presence when there is no window, and the reason
 * closing one is now allowed to mean "put it away" (see the close handler).
 *
 * Three items, which is the whole set that has an answer here. Show is the way
 * back. Open in browser is the escape hatch for everything the embedded window
 * is worse at than a real browser — a second view, devtools you already have
 * open, a profile with your extensions. Quit is the only way out, so it has to
 * be here.
 */
function createTray() {
  if (tray) return;
  // macOS wants a monochrome template image it can invert for the dark menu
  // bar and the selected state; the "Template" suffix is what tells Electron
  // (and AppKit) that it is one. Windows and Linux draw the icon as given.
  const icon = process.platform === "darwin" ? "trayTemplate.png" : "tray.png";
  try {
    tray = new Tray(nativeImage.createFromPath(path.join(ASSETS, icon)));
  } catch (err) {
    // The constructor itself failed, which on Windows and macOS is the only way
    // to have no tray at all. The window and the badge still work; only the
    // close-to-tray promise is off.
    console.log(`[shell] no tray available: ${err?.message || err}`);
    return;
  }
  // Constructing it is not the same as it appearing, so find out — the flag the
  // close handler reads stays false until the session confirms. Not awaited:
  // registration is a round trip on the session bus and nothing else here waits
  // on it, and a close arriving before it lands asks again for itself.
  void refreshTrayResidency(5000);
  tray.setToolTip(trayTooltip(needsYouCount));
  // A left click opens the menu on macOS by convention, so leave it alone
  // there; everywhere else a click on a tray icon is expected to bring the
  // window back, and the menu is on right-click.
  if (process.platform !== "darwin") tray.on("click", () => showWindow());
  rebuildTrayMenu();
}

function rebuildTrayMenu() {
  if (!tray) return;
  tray.setContextMenu(
    Menu.buildFromTemplate([
      // The count again, in words. The tooltip carries it too, but several
      // Linux status-bar implementations never show one.
      {
        label: needsYouCount
          ? `${needsYouCount} task${needsYouCount === 1 ? "" : "s"} waiting on you`
          : "Nothing is waiting on you",
        enabled: false,
      },
      { type: "separator" },
      { label: "Show Calandria", click: () => showWindow() },
      { label: "Open in browser", enabled: !!appUrl, click: () => appUrl && shell.openExternal(appUrl) },
      { type: "separator" },
      // `app.quit()`, never `app.exit()`: quitting has to go through
      // `before-quit`, which is the only place in-flight turns get drained.
      { label: "Quit Calandria", click: () => app.quit() },
    ]),
  );
}

/**
 * The dock/taskbar badge — the instance-wide "N need you" count, the same
 * number the app's own titlebar pill shows.
 *
 * Three platforms, two APIs. macOS and Linux take a number
 * (`app.setBadgeCount`, which is `dock.setBadge` underneath on macOS and a
 * Unity launcher entry on Linux — a no-op on desktops that have none, which is
 * why it is called unconditionally rather than probed). Windows has no numeric
 * badge at all: its taskbar overlay is a 16x16 image, so the digits are
 * pre-rendered PNGs and this picks one (see notifier.js's overlayIconName).
 */
function applyBadge(count) {
  needsYouCount = Number.isFinite(count) ? Math.max(0, count) : 0;
  if (process.platform === "win32") {
    const name = overlayIconName(needsYouCount);
    // The description is not decoration on Windows — it is what a screen reader
    // announces for the overlay, which is otherwise an unlabelled dot.
    win?.setOverlayIcon(
      name ? nativeImage.createFromPath(path.join(ASSETS, name)) : null,
      name ? `${needsYouCount} tasks waiting on you` : "",
    );
  } else {
    app.setBadgeCount(needsYouCount);
  }
  tray?.setToolTip(trayTooltip(needsYouCount));
  rebuildTrayMenu();
}

/**
 * Subscribe the main process to the app's own global event stream, over
 * loopback, and turn it into the two things a window cannot provide: an OS
 * notification and a badge.
 *
 * Same stream every browser tab reads (GET /api/events), and deliberately the
 * same division of labour — the server composed the notification, this renders
 * it. See notifier.js's header for why none of that policy is repeated here.
 */
function startEvents() {
  needsYou = new NeedsYou();
  events = new AppEvents({
    origin: appUrl,
    // The sidecars' env, not ours: supervisor.js may have repaired PATH and is
    // the authority on what the server was actually started with.
    serviceToken: (supervisor?.effectiveEnv || process.env).SERVICE_TOKEN || null,
    onLog: (line) => console.log(line),
    onProjects: (projects) => applyBadge(needsYou.seed(projects)),
    onEvent: (ev) => {
      if (ev.type === "notification") {
        notify(ev.payload);
        return;
      }
      const outcome = needsYou.apply(ev);
      if (outcome === "reseed") void events.refreshProjects();
      else if (outcome === "ok") applyBadge(needsYou.total);
    },
  });
  // Seed before subscribing: the badge should be right on the first frame,
  // not on the first event, and a fresh launch usually has tasks already
  // waiting from the last session.
  void events.refreshProjects();
  events.start();
}

/** Raise one server-composed notification. */
function notify(payload) {
  if (!payload || !Notification.isSupported()) return;
  const focused = !!win && !win.isDestroyed() && win.isVisible() && !win.isMinimized() && win.isFocused();
  const url = win && !win.isDestroyed() ? win.webContents.getURL() : "";
  if (!shouldNotify(payload, { focused, selectedTaskId: selectedTaskFromUrl(url) })) return;
  liveToasts.get(payload.id)?.close();
  const toast = new Notification({ title: payload.title, body: payload.body });
  liveToasts.set(payload.id, toast);
  toast.on("close", () => {
    if (liveToasts.get(payload.id) === toast) liveToasts.delete(payload.id);
  });
  toast.on("click", () => {
    showWindow();
    gotoTask(payload);
  });
  toast.show();
}

/**
 * Select the task a notification was about.
 *
 * Through the app's own `calandria:goto-task` window event — the same one the
 * browser channel and the service worker dispatch (app/shell/useShell.ts
 * listens for it), so the shell inherits whatever "go to this task" already
 * means, including switching projects. Written by evaluating in the page
 * rather than over IPC, for the reason the whole file has no preload: a bridge
 * would exist on every page the window ever loads, to serve one call.
 * Navigating to `?task=` would do the same job by throwing away the running SPA.
 */
function gotoTask(payload) {
  if (!payload?.taskId || !appUrl || !win || win.isDestroyed()) return;
  const detail = JSON.stringify({ projectId: payload.projectId || "", taskId: payload.taskId });
  win.webContents
    .executeJavaScript(`window.dispatchEvent(new CustomEvent("calandria:goto-task", { detail: ${detail} }))`)
    .catch(() => {});
}

function buildMenu() {
  // Without an application menu, macOS loses Cmd+C/V/A entirely — the roles
  // below are what wire the system shortcuts, not decoration.
  const isMac = process.platform === "darwin";
  return Menu.buildFromTemplate([
    ...(isMac ? [{ role: "appMenu" }] : []),
    { role: "fileMenu" },
    { role: "editMenu" },
    {
      label: "View",
      submenu: [
        { label: "Reload app", accelerator: "CmdOrCtrl+R", click: () => appUrl && win?.loadURL(appUrl) },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" },
        {
          label: "Open in browser",
          click: () => appUrl && shell.openExternal(appUrl),
        },
      ],
    },
    { role: "windowMenu" },
  ]);
}
