/* Calandria desktop shell — Electron main process.
 *
 * SPIKE CODE. See ./README.md and docs/DESKTOP_APP.md.
 *
 * Intentionally thin. Everything that can be tested without a display lives in
 * supervisor.js; this file is window + menu + lifecycle, and it holds exactly
 * one piece of policy: the renderer is a hardened browser tab pointed at
 * 127.0.0.1, not a privileged page. No preload, no nodeIntegration, no IPC —
 * the app already talks to its server over HTTP/SSE/WS and gains nothing from
 * a bridge, while a bridge would hand any XSS in the transcript renderer the
 * whole Node API.
 */
"use strict";

const { app, BrowserWindow, Menu, Notification, Tray, nativeImage, shell, dialog, session } = require("electron");
const fs = require("node:fs");
const path = require("node:path");
const { execFile } = require("node:child_process");
const log = require("electron-log/main");
const { Supervisor, preferredPorts } = require("./supervisor");
const {
  AppEvents,
  NeedsYou,
  overlayIconName,
  selectedTaskFromUrl,
  shouldNotify,
  trayTooltip,
} = require("./notifier");
const { confirmTrayResidency } = require("./tray-residency");
const {
  CHECK_INTERVAL_MS,
  FIRST_CHECK_DELAY_MS,
  RELEASES_URL,
  classifyUpdaterError,
  installFailureNotice,
  installStageOf,
  installStageTimeout,
  macBundlePath,
  parseActiveTurns,
  parseCodesign,
  quitAction,
  restartNotice,
  updateMenuItem,
  updaterDisposition,
} = require("./updater");

// Persistent logging, before anything else writes a line. Everything this file
// says through `console.log` — and every sidecar line the Supervisor relays
// through it — lands in electron-log's file as well as on stdout:
// ~/Library/Logs/Calandria/main.log on macOS, ~/.config/Calandria/logs/main.log
// on Linux, %APPDATA%\Calandria\logs\main.log on Windows (docs/DESKTOP_APP.md
// §6.6). The file exists for the one story stdout cannot tell: an update that
// fails on the way OUT of the process, after the drain, when the only observer
// is the terminal nobody launched a packaged app from. The console transport is
// pinned to the bare text so stdout stays byte-identical — desktop/e2e reads
// `[shell] …` lines off it with `startsWith`.
log.transports.console.format = "{text}";
log.transports.file.maxSize = 5 * 1024 * 1024;
Object.assign(console, log.functions);

// Where the server payload lives — the thing supervisor.js runs `node server.js`
// out of. Packaged, it is extraResources sitting NEXT TO the asar, not inside
// it: it holds native addons that dlopen from a real path and it is spawned as
// a child process, neither of which can see into an archive (staged by
// scripts/build-payload.js, mapped to resources/app-payload by the
// electron-builder config in package.json). Unpackaged, it is the checkout this
// file sits in, so `cd desktop && npm start` against a repo stays the developer
// flow. CALANDRIA_REPO_ROOT overrides both, which is how a packaged binary gets
// pointed at a working tree.
const REPO_ROOT =
  process.env.CALANDRIA_REPO_ROOT ||
  (app.isPackaged ? path.join(process.resourcesPath, "app-payload") : path.resolve(__dirname, ".."));
const LOADING_PAGE = `file://${path.join(__dirname, "loading.html")}`;
// Committed PNGs, regenerated by scripts/make-assets.py. Inside the asar when
// packaged, which is fine for both consumers: Tray and nativeImage read through
// Electron's own fs shim.
const ASSETS = path.join(__dirname, "assets");

let win = null;
let supervisor = null;
let appUrl = null;
let quitting = false;
// A fatal failure is reported once, by whichever path notices it first. A
// sidecar that dies DURING boot trips both of them: the Supervisor's `onExit`
// fires, and `supervisor.start()` then rejects with that same child's reason —
// so the user gets the specific dialog and a second, vaguer one stacked on it.
// In production the first `app.exit(1)` usually tears the process down before
// the second is drawn, which is what makes this a race rather than a constant;
// the interlock makes the outcome the same on a loaded machine as on an idle
// one. Same shape as `quitting` above, and checked alongside it.
let failed = false;
let tray = null;
// Whether that icon is actually IN a status area — which is a different fact
// from `tray` being an object, and the one the close handler needs. See
// tray-residency.js, and `refreshTrayResidency()` below for the rule that moves
// it. False until the session says otherwise, so nothing promises a tray it has
// not seen.
let trayHosted = false;
// Has the session ever answered? Only so the first answer is logged even when
// it agrees with the pessimistic default — a launch that found no status area
// has to say so.
let trayResidencyKnown = false;
// One close decision at a time: the handler now answers asynchronously, and a
// second X while the first is still asking would ask again rather than wait.
let closePending = false;
let events = null;
let needsYou = null;
let needsYouCount = 0;
// Live toasts by payload id, so a second notification about the same task
// replaces the first instead of stacking. The browser channel gets this from
// `Notification.tag`; Electron's main-process Notification has no tag, so the
// collapse is done by hand against the same id the server minted.
const liveToasts = new Map();
// The `electron-updater` singleton, or null when this install cannot update
// itself. Deliberately not required at the top of the file: on Linux that
// module's `autoUpdater` export picks its implementation on first property
// access, and inside a .deb it picks one that installs with `sudo dpkg -i`. See
// updater.js's linux-package case. Nothing here touches it before
// `updateDisposition.enabled` says so.
let updater = null;
let updateDisposition = null;
// phase: idle | checking | downloading | ready | none | error.
let updateState = { phase: "idle", version: null, error: null };
// Set only by the user answering the restart prompt. The drain reads it at the
// very end (see finishQuit) — an install is never something a quit does by
// itself.
let installOnQuit = false;
// A check the user started, so its outcome gets an answer instead of a silent
// log line. Cleared by whichever updater event answers it.
let manualCheck = false;
let updateTimer = null;
// The drain-tail watchdog (see finishQuit): one timer, re-armed per install
// stage, so a stage that is legitimately slow does not get the clock a stage
// that should be instant gets.
let installWatchdog = null;
let installStage = null;

// One shell per machine. This mirrors, at the UI layer, the single-process rule
// lib/db-lock.mjs enforces at the database layer: a second launch would spawn a
// second server, lose the lock race, and exit(1) with an error the user reads as
// a crash. Focusing the existing window is what they meant anyway.
if (!app.requestSingleInstanceLock()) {
  app.exit(0);
} else {
  app.on("second-instance", () => showWindow());
  main();
}

function main() {
  app.on("window-all-closed", () => {
    // Normally unreachable: the close handler below hides the window rather
    // than destroying it, on every platform (see "Close vs quit" in
    // docs/DESKTOP_APP.md §5.1). The one way here is a close that arrives
    // BEFORE boot() finished — that handler lets those through, since there is
    // no server to keep alive and no confirmed tray to be present in yet — and
    // there, quitting is exactly what the user asked for. Gated on the same
    // confirmed tray the close handler uses, rather than on the platform, so a
    // hide can never be mistaken for a quit.
    if (!trayHosted) app.quit();
  });

  app.on("activate", () => showWindow());

  // Quit is the only place in-flight turns can be drained: supervisor.stop()
  // POSTs /api/instance/drain and waits for the turns to settle before it
  // stops the sidecars. Hold the quit open for exactly as long as that takes.
  app.on("before-quit", async (event) => {
    if (quitting || !supervisor) return;
    quitting = true;
    event.preventDefault();
    // Nothing that arrives from here on has anywhere to go: the badge is about
    // to disappear with the process, and a toast raised during a shutdown is
    // one the user cannot act on.
    events?.stop();
    // Same reasoning for the update clock: a check that lands mid-drain has
    // nowhere to put its answer, and a download starting now would be thrown
    // away with the process.
    if (updateTimer) clearInterval(updateTimer);
    updateTimer = null;
    showDraining();
    try {
      await supervisor.stop();
    } finally {
      // Explicitly, before exit: a tray icon whose process is gone is left
      // behind as a dead slot by several Linux status-bar implementations.
      tray?.destroy();
      tray = null;
      trayHosted = false;
      trayResidencyKnown = false;
      // The update install, if there is one, happens HERE and only here —
      // after the drain, as the last thing the process does.
      finishQuit();
    }
  });

  app.whenReady().then(async () => {
    Menu.setApplicationMenu(buildMenu());
    announceShell();
    hardenSession();
    createWindow();
    await boot();
  });
}

function createWindow() {
  win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 720,
    minHeight: 480,
    backgroundColor: "#0b0d10",
    show: true,
    title: "Calandria",
    // A dark, borderless-ish title bar on macOS matches the app's own titlebar;
    // on Windows/Linux the native frame stays, since the app has no custom
    // window controls of its own to replace it with.
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    // With no native bar there is nowhere for the traffic lights to go but on
    // top of the page, so their position is a layout constant the WEB side has
    // to know: the app's titlebar reserves a matching left inset for them
    // (`.app.mac-chrome .titlebar` in app/globals.css) or the logo sits under
    // the buttons. Pinning it here rather than taking hiddenInset's default
    // makes that inset a number both sides can agree on — and y centres the
    // ~16px cluster in the 50px titlebar instead of the 28px bar Electron
    // assumes. tests/desktopWindowChrome.test.ts holds the two in step.
    ...(process.platform === "darwin" ? { trafficLightPosition: { x: 18, y: 17 } } : {}),
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      spellcheck: true,
    },
  });

  // The boot screen only while there is nothing better: a window recreated
  // after its predecessor was destroyed (macOS, dock click) must land on the
  // app, not on a spinner for a server that came up minutes ago.
  win.loadURL(appUrl || LOADING_PAGE);

  // Anything that isn't our own loopback origin opens in the user's real
  // browser: GitHub PR links, docs, a task's exposed service. A new
  // BrowserWindow for those would be a browser we then have to maintain.
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (isAppUrl(url)) return { action: "allow" };
    shell.openExternal(url);
    return { action: "deny" };
  });
  win.webContents.on("will-navigate", (event, url) => {
    if (isAppUrl(url) || url.startsWith("file://")) return;
    event.preventDefault();
    shell.openExternal(url);
  });

  // CLOSE VS QUIT — one rule on all three platforms: the X button (and Cmd+W)
  // HIDES the window, and quitting is something you ask for by name. The
  // reasoning, and what changed to allow it, is in docs/DESKTOP_APP.md §5.1.
  //
  // The short version: closing used to quit on Windows and Linux because
  // "leaving turns running invisibly with no window is worse than stopping
  // them" — and that was right while the shell had no way to be present
  // without a window. It now has one. The tray icon is on screen, it carries
  // the "N need you" count, and Show is one click away; a hidden Calandria is
  // no more invisible than a minimised one. Against that, close-to-quit on a
  // window whose whole job is supervising long agent turns means every
  // absent-minded X kills work in flight — and the drain that protects it
  // (which is real, and which desktop/e2e/03-quit-drain.spec.ts pins) only
  // makes the shutdown slower, not less unwanted.
  //
  // Hiding rather than destroying is also what keeps the renderer's state: the
  // SPA's open transcript, scroll position and SSE streams survive, so
  // reopening is instant instead of a cold reload. That is why macOS hides too
  // even though its convention would permit a real close — `activate` then
  // shows the same window instead of building a new one.
  //
  // Three escapes, all deliberate, and the first is the load-bearing one: this
  // hides only while a status area is ACTUALLY DRAWING the tray icon. The gate
  // used to be `new Tray()` not throwing, which is a much weaker thing and is
  // not true of the case it was written for: on Linux the constructor succeeds
  // on a session with no status-notifier host, so the window hid into nowhere
  // and the "open it again from the tray icon" toast named an icon that did not
  // exist (tray-residency.js carries the measurement). Refusing to hide
  // somewhere the user cannot get the app back from is the old rationale, still
  // correct — it just needs the session's answer rather than Electron's. A
  // close BEFORE boot() finished is let through for the same reason (no server
  // to keep alive, no tray yet), and `window-all-closed` turns it into a quit.
  // And a close DURING the drain is let through as well — by then the user has seen
  // the drain state and asked twice, and `supervisor.stop()` is bounded anyway,
  // so the wait cannot outlive the grace.
  win.on("close", (event) => {
    if (quitting || !supervisor) return;
    // Always prevented here and resolved in `decideClose()`: the answer is a
    // question for the session bus, which cannot be asked synchronously, and a
    // close that is allowed through cannot be taken back.
    event.preventDefault();
    if (closePending) return;
    closePending = true;
    void decideClose().finally(() => {
      closePending = false;
    });
  });

  win.on("closed", () => {
    win = null;
  });
}

function isAppUrl(url) {
  if (!appUrl) return false;
  try {
    const u = new URL(url);
    return u.origin === new URL(appUrl).origin;
  } catch {
    return false;
  }
}

function announceShell() {
  // The one thing the page is told about its container, and it is told in the
  // user agent because that is the only channel that is already per-CLIENT: the
  // same server can be open in this window and in an ordinary browser tab at
  // the same moment, so an env var on the sidecars or a flag in the per-instance
  // `window.__FEATURES` bundle would answer one of them with the other's truth.
  //
  // What it buys, today, is one sentence: Settings → Notifications reads
  // `Notification.permission`, which hardenSession() below makes "denied", and
  // saying "you've blocked notifications for this site" to somebody who is
  // getting OS toasts from us the whole time sends them looking for a browser
  // setting this window does not have. app/shell/useNotifications.ts matches
  // this token (isDesktopShell) and reports "handled by the desktop app".
  //
  // Appended rather than replacing, so the Chrome/Electron versions the app may
  // reasonably branch on survive; must be set before the first load.
  app.userAgentFallback = `${app.userAgentFallback} Calandria-Desktop/${app.getVersion()}`;
}

function hardenSession() {
  // Default-deny, so a future dependency can't quietly acquire the camera.
  //
  // `notifications` is denied HERE and raised from the main process instead —
  // the one permission this handler used to grant. Both channels read the same
  // server-composed payload off /api/events, so granting it would give the user
  // two toasts for every event: Chromium's, from app/shell/useNotifications.ts,
  // and the shell's. The main process wins because it is the half that can
  // still fire with the window hidden to the tray or destroyed, can raise the
  // window and select the task on click, and owns the dock/taskbar badge that
  // has to agree with what it just said. The renderer's channel stands down
  // cleanly on its own: `notificationPermission()` returns something that isn't
  // `granted` and the hook returns before constructing anything. It returns
  // `desktop_shell`, not the raw `denied`, off the token announceShell() sets
  // above — so Settings can say the desktop app owns this rather than telling
  // the user they blocked a site setting this window cannot open.
  session.defaultSession.setPermissionRequestHandler((_wc, permission, callback) => {
    callback(permission === "clipboard-sanitized-write");
  });
  // The request handler is NOT enough to switch the page's channel off, and
  // this is the half that actually does it. `useNotifications.ts` reads
  // `Notification.permission` — a permission CHECK, which Electron answers with
  // a hardcoded "granted" when no check handler is set, whatever the request
  // handler would have said. So the hook would have sailed past its own guard
  // and shown the duplicate toast without ever asking. Only notifications are
  // named here: every other check keeps Electron's default answer, so this
  // adds one denial rather than quietly tightening a surface the request
  // handler above is the policy for.
  session.defaultSession.setPermissionCheckHandler((_wc, permission) => permission !== "notifications");
}

async function boot() {
  supervisor = new Supervisor({
    repoRoot: REPO_ROOT,
    // PORT/PTY_PORT are documented as env the shell understands, so read them
    // here — the Supervisor's own 3000/3001 are the fallback, not the policy.
    // Still preferences: a busy one is stepped past (see pickPorts).
    ...preferredPorts(process.env),
    resourcesPath: app.isPackaged ? process.resourcesPath : null,
    onLog: (line) => {
      // Two consumers: the terminal a developer launched us from, and the
      // loading screen's off-screen `#log`. The boot screen shows a spinner
      // rather than these lines — a scrolling wall of sidecar output is not
      // what someone waiting for the window wants to read — but they are still
      // pushed across, because that element is the only place the supervisor's
      // FIRST lines survive: Electron stdout capture starts after launch has
      // resolved, so desktop/e2e reads them back off the page instead.
      console.log(line);
      // executeJavaScript rather than IPC: the boot screen is the only consumer
      // and adding a preload for it would mean shipping a bridge into every
      // page the window later loads, including the app itself.
      //
      // The write is done HERE rather than by calling a helper the boot screen
      // defines, because loading.html's CSP is `default-src 'none'` and that
      // blocks its own inline <script> — so a `window.__log` defined in the page
      // never exists, and the `&&` guard this used to have made that failure
      // completely silent (the boot screen simply stayed blank for every launch
      // there has ever been; found by desktop/e2e/01-shell.spec.ts). A
      // main-process evaluation is not subject to the page's CSP, so pushing the
      // DOM write across keeps the strict policy AND makes the log show up.
      // Only while the boot screen is the page: once appUrl is set the window is
      // on the app, which has no #log and no interest in being evaluated into on
      // every line the sidecars print for the rest of the session.
      if (appUrl) return;
      const write = `(() => { const el = document.getElementById("log"); if (!el) return; el.textContent += ${JSON.stringify(line + "\n")}; el.scrollTop = el.scrollHeight; })()`;
      win?.webContents.executeJavaScript(write).catch(() => {});
    },
    onExit: ({ name, code, dbLockHeld }) => {
      if (quitting || failed) return;
      failed = true;
      // A sidecar dying while the app is up is not recoverable in place: the
      // renderer's SSE streams are already broken and the db lock may be gone.
      const detail = dbLockHeld
        ? "Another Calandria instance is already running against this database.\n\nQuit that one first, or open it in your browser."
        : `The ${name} process exited unexpectedly (code ${code}).\n\n${supervisor.recentLog(15)}`;
      dialog.showErrorBox("Calandria stopped", detail);
      app.exit(1);
    },
  });

  try {
    const { url } = await supervisor.start();
    appUrl = url;
    await win?.loadURL(url);
    win?.setTitle("Calandria");
    // After the app is up, not before: the tray's "Open in browser" needs a
    // URL, and the event stream needs a server to subscribe to.
    createTray();
    startEvents();
    // After the tray, because the tray menu is where an available update is
    // advertised, and the first check is on a timer anyway.
    //
    // Its own try, INSIDE this one: everything from here down is a running app,
    // and the catch below reports a failure to start. A bad require or a
    // malformed feed config must not turn a working session into "Calandria
    // could not start" — an app that cannot check for updates still works.
    try {
      await startUpdater();
      // An install that failed on the way out of the LAST session could not be
      // shown then (see finishQuit); this is the first moment it can be.
      await reportLastInstallFailure();
    } catch (err) {
      console.log(`[shell] auto-update unavailable: ${err?.message || err}`);
    }
  } catch (err) {
    // `onExit` gets first claim when the failure was a sidecar dying, because
    // it knows WHICH one and whether the database was already held; this path
    // only has the rejection `start()` re-raised from it. Nothing left to do —
    // that path has already shown its dialog and asked for the exit.
    if (failed) return;
    failed = true;
    dialog.showErrorBox("Calandria could not start", `${err?.message || err}\n\n${supervisor?.recentLog(20) || ""}`);
    app.exit(1);
  }
}

/**
 * What quitting looks like while `supervisor.stop()` waits for the turns.
 *
 * Two signals because they answer to two places. The TITLE is what a window
 * manager shows, and on macOS it is the only one that matters — the window
 * stays and the user is looking at the dock. The OVERLAY is on the page, which
 * is where the eyes are on every platform, and it is also the only cue on a
 * desktop that draws no title bar at all. The page underneath is a live app
 * whose server is being shut down out from under it, so leaving it alone would
 * mean the last thing the user sees is a UI going wrong rather than one being
 * put away.
 *
 * Written from the main process, like the boot log and for the same reason:
 * the app serves its own CSP and a main-process evaluation is not subject to
 * it, so nothing here depends on the page cooperating. Best-effort throughout —
 * a window mid-navigation, or already gone, must not hold up the quit.
 */
function showDraining() {
  // Quit can now be asked for from the tray with the window hidden, so put it
  // back on screen first — otherwise the two signals below are written to
  // something nobody can see and the shutdown looks like a hang. Deliberately
  // NOT showWindow(): that builds a window when there isn't one, and a shell
  // that opens a fresh window on its way out is worse than a quiet exit.
  if (win && !win.isDestroyed()) {
    if (win.isMinimized()) win.restore();
    win.show();
  }
  win?.setTitle("Calandria — finishing in-flight turns…");
  win?.webContents.executeJavaScript(DRAIN_OVERLAY).catch(() => {});
}

const DRAIN_OVERLAY = `(() => {
  if (document.getElementById("calandria-draining")) return;
  const el = document.createElement("div");
  el.id = "calandria-draining";
  el.setAttribute("role", "status");
  el.style.cssText = [
    "position:fixed", "inset:0", "z-index:2147483647",
    "display:flex", "flex-direction:column", "align-items:center", "justify-content:center", "gap:10px",
    "background:rgba(11,13,16,.92)", "color:#e6e8eb", "-webkit-backdrop-filter:blur(2px)", "backdrop-filter:blur(2px)",
    'font:14px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
  ].join(";");
  const h = document.createElement("div");
  h.style.cssText = "font-size:16px;font-weight:600;letter-spacing:.2px";
  h.textContent = "Finishing in-flight turns…";
  const sub = document.createElement("div");
  sub.style.cssText = "color:#8b939c;font-size:12.5px";
  sub.textContent = "Calandria is settling running sessions before it stops. This window closes on its own.";
  el.append(h, sub);
  document.body.appendChild(el);
})()`;

/**
 * Put the window in front, from wherever it currently is — hidden to the tray,
 * minimised, behind the editor, or (macOS, after a real destroy) not there at
 * all. Every "come back" path goes through here: the tray's Show, a tray click,
 * `activate`, a second launch, and a notification click.
 */
function showWindow() {
  if (!win || win.isDestroyed()) {
    createWindow();
    return;
  }
  if (win.isMinimized()) win.restore();
  win.show();
  win.focus();
}

/**
 * Hide, or quit — decided by asking the session whether the tray icon is really
 * there, not by trusting that it was there at boot.
 *
 * Re-asked on every close ON PURPOSE, because the way this shell loses a window
 * is a status-notifier host that goes away MID-SESSION: Electron offers no
 * callback for it, so the only cheap moment to notice is the moment the answer
 * decides something. That is also why there is no `NameOwnerChanged`
 * subscription here — it would mean a long-lived `gdbus monitor` child for a
 * fact nothing consults in between.
 *
 * Budgeted at 1.5 s and retried inside that, so a panel that is restarting is
 * waited through rather than read as gone. A probe that cannot ANSWER leaves
 * the last answer standing (see `refreshTrayResidency`), so a machine with no
 * D-Bus CLI keeps whatever boot established rather than flipping on a timeout.
 */
async function decideClose() {
  const hosted = await refreshTrayResidency(1500);
  // The quit path may have started while we were asking — `before-quit` shows
  // the window again for the drain, so hiding it now would undo that.
  if (quitting) return;
  if (!hosted) {
    // Nowhere to hide into, so closing means quitting, and `app.quit()` is what
    // keeps the drain (and the on-screen wait for it) in the chain.
    app.quit();
    return;
  }
  if (!win || win.isDestroyed()) return;
  win.hide();
  announceTrayResidency();
}

/**
 * Re-read whether the tray icon is in a status area, and report the current
 * belief.
 *
 * ONE RULE, and it is the whole reason this is not a boolean assignment:
 * `trayHosted` moves only when the session gives an ANSWER. A probe that could
 * not run — no `gdbus`, no `dbus-send`, a timed-out call — is not evidence that
 * a working tray disappeared, and treating it as one would turn every X on a
 * healthy desktop into a quit.
 */
async function refreshTrayResidency(timeoutMs) {
  if (!tray) return false;
  const verdict = await confirmTrayResidency({ pid: process.pid, timeoutMs });
  if (verdict.hosted === null) {
    console.log(
      `[shell] could not confirm the tray icon (${verdict.reason}) — keeping the last answer: ` +
        `${trayHosted ? "hosted" : "not hosted"}`,
    );
    return trayHosted;
  }
  // Logged on the first answer and on every change after it, never on a repeat:
  // the first is what a launch needs to state (and what the e2e suite branches
  // on, since the two close behaviours are both correct and only the session
  // says which), the rest are the mid-session flips this exists to catch.
  if (!trayResidencyKnown || verdict.hosted !== trayHosted) {
    console.log(
      verdict.hosted
        ? `[shell] tray icon confirmed in the status area (${verdict.reason})`
        : `[shell] tray icon is not in any status area (${verdict.reason}) — closing the window will quit`,
    );
  }
  trayResidencyKnown = true;
  trayHosted = verdict.hosted;
  return trayHosted;
}

// Hiding a window is the one action here with no visible result, and on
// Windows and Linux it is also a CHANGE from what this shell used to do (the X
// used to quit). Say so once per launch, through the same channel everything
// else here uses, so the first close doesn't read as a crash. Once only: a
// reminder every time would be the nag that makes people avoid the button.
let trayResidencyAnnounced = false;

function announceTrayResidency() {
  // `trayHosted`, never `tray`: this is the one message that tells the user
  // where the window went, so raising it on a session with no icon is worse
  // than saying nothing at all. `decideClose()` has already re-confirmed by the
  // time this runs, and only calls it on the hide branch.
  if (trayResidencyAnnounced || !trayHosted || !Notification.isSupported()) return;
  trayResidencyAnnounced = true;
  new Notification({
    title: "Calandria is still running",
    body: "Turns keep going in the background. Open it again from the tray icon, or quit from its menu.",
  }).show();
}

/**
 * The tray icon: the shell's presence when there is no window, and the reason
 * closing one is now allowed to mean "put it away" (see the close handler).
 *
 * Three items, which is the whole set that has an answer here. Show is the way
 * back. Open in browser is the escape hatch for everything the embedded window
 * is worse at than a real browser — a second view, devtools you already have
 * open, a profile with your extensions. Quit is the only way out, so it has to
 * be here.
 */
function createTray() {
  if (tray) return;
  // macOS wants a monochrome template image it can invert for the dark menu
  // bar and the selected state; the "Template" suffix is what tells Electron
  // (and AppKit) that it is one. Windows and Linux draw the icon as given.
  const icon = process.platform === "darwin" ? "trayTemplate.png" : "tray.png";
  try {
    tray = new Tray(nativeImage.createFromPath(path.join(ASSETS, icon)));
  } catch (err) {
    // The constructor itself failed, which on Windows and macOS is the only way
    // to have no tray at all. The window and the badge still work; only the
    // close-to-tray promise is off.
    console.log(`[shell] no tray available: ${err?.message || err}`);
    return;
  }
  // Constructing it is not the same as it appearing, so find out — the flag the
  // close handler reads stays false until the session confirms. Not awaited:
  // registration is a round trip on the session bus and nothing else here waits
  // on it, and a close arriving before it lands asks again for itself.
  void refreshTrayResidency(5000);
  tray.setToolTip(trayTooltip(needsYouCount));
  // A left click opens the menu on macOS by convention, so leave it alone
  // there; everywhere else a click on a tray icon is expected to bring the
  // window back, and the menu is on right-click.
  if (process.platform !== "darwin") tray.on("click", () => showWindow());
  rebuildTrayMenu();
}

function rebuildTrayMenu() {
  if (!tray) return;
  tray.setContextMenu(
    Menu.buildFromTemplate([
      // The count again, in words. The tooltip carries it too, but several
      // Linux status-bar implementations never show one.
      {
        label: needsYouCount
          ? `${needsYouCount} task${needsYouCount === 1 ? "" : "s"} waiting on you`
          : "Nothing is waiting on you",
        enabled: false,
      },
      { type: "separator" },
      { label: "Show Calandria", click: () => showWindow() },
      { label: "Open in browser", enabled: !!appUrl, click: () => appUrl && shell.openExternal(appUrl) },
      { type: "separator" },
      // The update affordance that survives a hidden window, which is this
      // app's usual state. Its label carries the whole status — "Check for
      // updates…", "Downloading 0.5.0…", "Restart to update to 0.5.0", or the
      // reason this install cannot update itself. This menu is already rebuilt
      // on every badge change, and setUpdateState() rebuilds it whenever that
      // label moves.
      { ...trayUpdateItem(), click: () => void checkForUpdates(true) },
      { type: "separator" },
      // `app.quit()`, never `app.exit()`: quitting has to go through
      // `before-quit`, which is the only place in-flight turns get drained.
      { label: "Quit Calandria", click: () => app.quit() },
    ]),
  );
}

/**
 * The dock/taskbar badge — the instance-wide "N need you" count, the same
 * number the app's own titlebar pill shows.
 *
 * Three platforms, two APIs. macOS and Linux take a number
 * (`app.setBadgeCount`, which is `dock.setBadge` underneath on macOS and a
 * Unity launcher entry on Linux — a no-op on desktops that have none, which is
 * why it is called unconditionally rather than probed). Windows has no numeric
 * badge at all: its taskbar overlay is a 16x16 image, so the digits are
 * pre-rendered PNGs and this picks one (see notifier.js's overlayIconName).
 */
function applyBadge(count) {
  needsYouCount = Number.isFinite(count) ? Math.max(0, count) : 0;
  if (process.platform === "win32") {
    const name = overlayIconName(needsYouCount);
    // The description is not decoration on Windows — it is what a screen reader
    // announces for the overlay, which is otherwise an unlabelled dot.
    win?.setOverlayIcon(
      name ? nativeImage.createFromPath(path.join(ASSETS, name)) : null,
      name ? `${needsYouCount} tasks waiting on you` : "",
    );
  } else {
    app.setBadgeCount(needsYouCount);
  }
  tray?.setToolTip(trayTooltip(needsYouCount));
  rebuildTrayMenu();
}

/**
 * Subscribe the main process to the app's own global event stream, over
 * loopback, and turn it into the two things a window cannot provide: an OS
 * notification and a badge.
 *
 * Same stream every browser tab reads (GET /api/events), and deliberately the
 * same division of labour — the server composed the notification, this renders
 * it. See notifier.js's header for why none of that policy is repeated here.
 */
function startEvents() {
  needsYou = new NeedsYou();
  events = new AppEvents({
    origin: appUrl,
    // The sidecars' env, not ours: supervisor.js may have repaired PATH and is
    // the authority on what the server was actually started with.
    serviceToken: (supervisor?.effectiveEnv || process.env).SERVICE_TOKEN || null,
    onLog: (line) => console.log(line),
    onProjects: (projects) => applyBadge(needsYou.seed(projects)),
    onEvent: (ev) => {
      if (ev.type === "notification") {
        notify(ev.payload);
        return;
      }
      const outcome = needsYou.apply(ev);
      if (outcome === "reseed") void events.refreshProjects();
      else if (outcome === "ok") applyBadge(needsYou.total);
    },
  });
  // Seed before subscribing: the badge should be right on the first frame,
  // not on the first event, and a fresh launch usually has tasks already
  // waiting from the last session.
  void events.refreshProjects();
  events.start();
}

/** Raise one server-composed notification. */
function notify(payload) {
  if (!payload || !Notification.isSupported()) return;
  const focused = !!win && !win.isDestroyed() && win.isVisible() && !win.isMinimized() && win.isFocused();
  const url = win && !win.isDestroyed() ? win.webContents.getURL() : "";
  if (!shouldNotify(payload, { focused, selectedTaskId: selectedTaskFromUrl(url) })) return;
  liveToasts.get(payload.id)?.close();
  const toast = new Notification({ title: payload.title, body: payload.body });
  liveToasts.set(payload.id, toast);
  toast.on("close", () => {
    if (liveToasts.get(payload.id) === toast) liveToasts.delete(payload.id);
  });
  toast.on("click", () => {
    showWindow();
    gotoTask(payload);
  });
  toast.show();
}

/**
 * Select the task a notification was about.
 *
 * Through the app's own `calandria:goto-task` window event — the same one the
 * browser channel and the service worker dispatch (app/shell/useShell.ts
 * listens for it), so the shell inherits whatever "go to this task" already
 * means, including switching projects. Written by evaluating in the page
 * rather than over IPC, for the reason the whole file has no preload: a bridge
 * would exist on every page the window ever loads, to serve one call.
 * Navigating to `?task=` would do the same job by throwing away the running SPA.
 */
function gotoTask(payload) {
  if (!payload?.taskId || !appUrl || !win || win.isDestroyed()) return;
  const detail = JSON.stringify({ projectId: payload.projectId || "", taskId: payload.taskId });
  win.webContents
    .executeJavaScript(`window.dispatchEvent(new CustomEvent("calandria:goto-task", { detail: ${detail} }))`)
    .catch(() => {});
}

/* ------------------------------------------------------------------------- *
 * Auto-update.
 *
 * Two entry points, both explicit about which one is running: a check on a
 * timer after launch (and every six hours a long-lived shell stays up), and a
 * "Check for updates" item the user can press. Downloading is automatic;
 * INSTALLING NEVER IS. See updater.js's header for why, and finishQuit() below
 * for the mechanism.
 * ------------------------------------------------------------------------- */

async function startUpdater() {
  updateDisposition = updaterDisposition({
    env: process.env,
    platform: process.platform,
    packaged: app.isPackaged,
    // Set by the AppImage runtime to the path of the running image. The only
    // artifact on Linux that can replace itself in place.
    appImage: process.env.APPIMAGE || null,
    mac: await macBundleFacts(),
  });
  // Paint the reason into both menus even when the answer is no — a greyed
  // "Updates come from your package manager" is information; a missing item
  // reads as an app that has no updates at all.
  refreshUpdateMenus();
  if (!updateDisposition.enabled) {
    console.log(`[shell] auto-update off (${updateDisposition.code}): ${updateDisposition.reason}`);
    return;
  }

  updater = require("electron-updater").autoUpdater;
  // electron-log directly, debug level included: MacUpdater's account of its
  // proxy server and the Squirrel handoff is at debug, and it is the account a
  // failed install needs.
  updater.logger = log.scope("updater");
  updater.autoDownload = true;
  // THE setting. electron-updater's default is true, which installs from an
  // `app.on("quit")` handler — and `quit` fires after our `before-quit` has
  // already drained and called app.exit(). That would either skip the install
  // silently or run it over turns that were still settling. We own the moment
  // instead: finishQuit() calls quitAndInstall() as the last act of the drain.
  updater.autoInstallOnAppQuit = false;

  updater.on("checking-for-update", () => setUpdateState({ phase: "checking" }));
  updater.on("update-available", (info) => setUpdateState({ phase: "downloading", version: info?.version || null }));
  updater.on("update-not-available", () => {
    setUpdateState({ phase: "none" });
    answerManualCheck("Calandria is up to date", `You are running ${app.getVersion()}.`);
  });
  updater.on("update-downloaded", (info) => {
    setUpdateState({ phase: "ready", version: info?.version || null });
    manualCheck = false;
    announceUpdate();
  });
  updater.on("error", (err) => {
    // Past the drain this error is the install failing, and finishQuit() owns
    // that: it records the failure for the next launch and exits. A menu
    // refresh or a dialog here would be raised against a tray that is already
    // destroyed and a window on its way out.
    if (quitting) return;
    const { message, fatal } = classifyUpdaterError(err);
    console.log(`[shell] update check failed: ${message}`);
    setUpdateState({ phase: "error", error: message });
    const wasManual = manualCheck;
    answerManualCheck("Could not check for updates", message);
    if (!fatal) return;
    // Squirrel.Mac cannot update an app whose signature it cannot read. That is
    // a property of the build, not a transient, so stop asking — and SAY so,
    // once, even when nobody pressed anything: an automatic check that found
    // this used to be a console.log line in a terminal no packaged app has.
    if (updateTimer) clearInterval(updateTimer);
    updateTimer = null;
    if (!wasManual && Notification.isSupported()) {
      const toast = new Notification({ title: "Calandria cannot update itself", body: message });
      toast.on("click", () => void shell.openExternal(RELEASES_URL));
      toast.show();
    }
  });

  setTimeout(() => void checkForUpdates(false), FIRST_CHECK_DELAY_MS).unref();
  updateTimer = setInterval(() => void checkForUpdates(false), CHECK_INTERVAL_MS);
  updateTimer.unref();
}

/**
 * What a packaged macOS build knows about itself before the first check: where
 * the bundle is, and what `codesign` says about it. updater.js's
 * `macDisposition()` turns that into the three "this install cannot update"
 * answers that used to be discovered at install time, on the way out of the
 * process, where nothing could show them.
 *
 * Best-effort by contract. `codesign` is in every macOS install, but a probe
 * that fails (killed by the 5s timeout, missing, odd output) reports
 * `signature: "unknown"`, which the policy leaves alone — a failed probe must
 * not disable a working updater. Null off macOS and in development, where the
 * policy has already answered.
 */
async function macBundleFacts() {
  if (process.platform !== "darwin" || !app.isPackaged) return null;
  const bundlePath = macBundlePath(process.execPath);
  if (!bundlePath) return null;
  const result = await new Promise((resolve) => {
    execFile(
      "/usr/bin/codesign",
      ["-dv", "--verbose=4", bundlePath],
      { timeout: 5000, maxBuffer: 1024 * 1024 },
      (err, stdout, stderr) => resolve({ code: err ? (typeof err.code === "number" ? err.code : 1) : 0, stdout, stderr }),
    );
  });
  const verdict = parseCodesign(result);
  console.log(
    `[shell] bundle ${bundlePath}: signature ${verdict.signature}${verdict.authority ? ` (${verdict.authority})` : ""}`,
  );
  return { bundlePath, signature: verdict.signature };
}

// One shape, two menus: label and enabled come from updater.js so the tray and
// the application menu can never disagree about what the update state is.
function trayUpdateItem() {
  return updateMenuItem({ ...updateState, disposition: updateDisposition });
}

function setUpdateState(patch) {
  const before = updateMenuItem({ ...updateState, disposition: updateDisposition });
  updateState = {
    ...updateState,
    ...patch,
    // Only an error phase carries an error, so a later success clears the old
    // one rather than leaving a stale sentence attached to a fine state.
    error: patch.phase === "error" ? patch.error || null : null,
  };
  const after = updateMenuItem({ ...updateState, disposition: updateDisposition });
  if (after.label === before.label && after.enabled === before.enabled) return;
  refreshUpdateMenus();
}

// Both menus, because they cover different situations. The tray is the one that
// works when the window is hidden — which is the normal resting state of this
// app, so an update prompt that only exists inside the window is one nobody
// sees. The application menu is the one that exists when there is no tray at
// all (no status area, or the Tray constructor failed), where the window is by
// definition still on screen.
function refreshUpdateMenus() {
  rebuildTrayMenu();
  Menu.setApplicationMenu(buildMenu());
}

async function checkForUpdates(manual) {
  if (!updater) {
    if (manual) {
      // A macOS install that cannot update itself is one that needs the user
      // to go and get the release, so the dialog offers the trip. The other
      // codes (off, dev build, package manager) have somewhere else to go.
      const needsDownload = /^mac-/.test(updateDisposition?.code || "");
      const { response } = await messageBox({
        type: "info",
        message: needsDownload ? "This install cannot update itself" : "Automatic updates are off",
        detail: updateDisposition?.reason || "This build does not update itself.",
        buttons: needsDownload ? ["Download latest release", "OK"] : ["OK"],
        defaultId: 0,
        cancelId: needsDownload ? 1 : 0,
      });
      if (needsDownload && response === 0) void shell.openExternal(RELEASES_URL);
    }
    return;
  }
  // Already downloaded: the button the user just pressed means "get on with
  // it", not "check again".
  if (updateState.phase === "ready") {
    if (manual) await requestInstall();
    return;
  }
  if (updateState.phase === "checking" || updateState.phase === "downloading") return;
  if (manual) manualCheck = true;
  try {
    await updater.checkForUpdates();
  } catch (err) {
    // Rejections and the "error" event overlap; whichever arrives first
    // answers, and the classifier makes the two say the same thing.
    const { message } = classifyUpdaterError(err);
    console.log(`[shell] update check failed: ${message}`);
    setUpdateState({ phase: "error", error: message });
    answerManualCheck("Could not check for updates", message);
  }
}

function answerManualCheck(message, detail) {
  if (!manualCheck) return;
  manualCheck = false;
  void messageBox({ type: "info", message, detail, buttons: ["OK"] });
}

/**
 * The update-is-ready announcement, for an app whose window is usually hidden.
 *
 * Three surfaces, in order of how likely they are to be seen: an OS
 * notification (which survives a hidden window and carries a click), the tray
 * item's label, and the application menu. Deliberately NOT a dialog — a modal
 * raised against a window in the tray is a modal nobody sees, and on some
 * platforms it is a modal nobody can dismiss either.
 */
function announceUpdate() {
  console.log(`[shell] update ${updateState.version} downloaded and ready`);
  if (!Notification.isSupported()) return;
  const toast = new Notification({
    title: `Calandria ${updateState.version || "update"} is ready`,
    body: "Click to restart and install. In-flight turns are settled first.",
  });
  toast.on("click", () => {
    showWindow();
    void requestInstall();
  });
  toast.show();
}

/**
 * The one path from "an update exists" to "the app restarts", and the only
 * writer of `installOnQuit`.
 *
 * It ends in `app.quit()` — never `app.exit()`, and never
 * `updater.quitAndInstall()` directly — so the restart goes through
 * `before-quit` and gets the same drain a tray Quit gets. Routing an update
 * around that drain is the specific failure this whole feature is written to
 * avoid.
 */
async function requestInstall() {
  if (!updater || updateState.phase !== "ready") return;
  const active = await activeTurnCount();
  const { response } = await messageBox({
    type: "question",
    buttons: ["Restart and update", "Later"],
    defaultId: 0,
    cancelId: 1,
    message: `Calandria ${updateState.version || ""} is ready to install`.replace(/\s+/g, " "),
    detail: restartNotice(active),
  });
  if (response !== 0) return;
  installOnQuit = true;
  app.quit();
}

/**
 * How many turns are running, read-only.
 *
 * GET /api/instance/metrics rather than the drain endpoint, which is the other
 * thing that knows and answers by aborting them. Best-effort by contract: a
 * null just makes the restart prompt say less.
 */
async function activeTurnCount() {
  if (!appUrl) return null;
  const token = (supervisor?.effectiveEnv || process.env).SERVICE_TOKEN;
  try {
    const res = await fetch(`${appUrl}/api/instance/metrics`, {
      headers: token ? { "x-service-token": token } : {},
      signal: AbortSignal.timeout(2000),
    });
    if (!res.ok) return null;
    return parseActiveTurns(await res.text());
  } catch {
    return null;
  }
}

/**
 * The end of the drain, and the only place an update is ever installed.
 *
 * `quitAndInstall` calls `app.quit()` itself, which re-enters `before-quit` —
 * harmless, because `quitting` is already true there and the handler returns
 * without preventing it. If the handoff does not take the process down, the
 * watchdog does: a drained shell with no sidecars left is not something to
 * leave on screen.
 *
 * The watchdog is STAGED, and on macOS it has to be. With `autoInstallOnAppQuit`
 * off, MacUpdater's `quitAndInstall()` is what first hands the zip to
 * Squirrel.Mac — Squirrel then fetches it from electron-updater's local proxy,
 * extracts the bundle, verifies its signature, stages it, and only THEN quits
 * the app. That is tens of seconds to minutes, and the fixed 10s exit this
 * used to arm cut it off every time: the app went down mid-install and came
 * back unchanged. Squirrel reports its stages on Electron's native
 * `autoUpdater` (MacUpdater drives it but does not re-emit), so that is what
 * re-arms the clock here — long while Squirrel is demonstrably working, short
 * once it has staged the bundle and short before it has said anything.
 *
 * Whatever goes wrong here goes wrong in the one place it cannot be shown: the
 * tray is destroyed and the window is on its way out. So a failure is written
 * down (`recordInstallFailure`) and the NEXT launch reports it, with the log
 * file named, instead of relaunching unchanged as if nothing happened.
 */
function finishQuit() {
  if (quitAction({ installRequested: installOnQuit, phase: updateState.phase }) !== "install") {
    app.exit(0);
    return;
  }
  console.log(`[shell] drained; installing ${updateState.version || "update"}`);
  armInstallWatchdog("handoff");
  if (process.platform === "darwin") {
    const native = require("electron").autoUpdater;
    for (const event of ["checking-for-update", "update-available", "update-downloaded", "before-quit-for-update"]) {
      native.on(event, () => {
        const stage = installStageOf(event);
        console.log(`[shell] squirrel: ${event}${stage ? ` → ${stage}` : ""}`);
        if (stage) armInstallWatchdog(stage);
      });
    }
    native.on("update-not-available", () => console.log("[shell] squirrel: update-not-available (nothing staged)"));
    native.on("error", (err) => {
      const { message } = classifyUpdaterError(err);
      console.log(`[shell] install failed (${installStage}): ${message}`);
      recordInstallFailure({ stage: "error", message });
      app.exit(0);
    });
  }
  try {
    // isSilent false so a Windows user sees the installer they are agreeing to;
    // isForceRunAfter true so "restart and update" actually restarts.
    updater.quitAndInstall(false, true);
  } catch (err) {
    const { message } = classifyUpdaterError(err);
    console.log(`[shell] install failed: ${message}`);
    recordInstallFailure({ stage: "error", message });
    app.exit(0);
  }
}

function armInstallWatchdog(stage) {
  installStage = stage;
  if (installWatchdog) clearTimeout(installWatchdog);
  const ms = installStageTimeout(stage);
  installWatchdog = setTimeout(() => {
    console.log(`[shell] installer did not take the app down after ${Math.round(ms / 1000)}s (${stage}); exiting`);
    recordInstallFailure({ stage, message: "" });
    app.exit(0);
  }, ms);
  installWatchdog.unref();
}

// Where a failed install leaves its note for the next launch. userData rather
// than the log: the log is for reading, this is a flag, consumed on sight.
function installFailureFile() {
  return path.join(app.getPath("userData"), "update-install-failed.json");
}

function recordInstallFailure({ stage, message }) {
  try {
    const record = { version: updateState.version, stage, message, at: new Date().toISOString() };
    fs.writeFileSync(installFailureFile(), JSON.stringify(record));
  } catch (err) {
    console.log(`[shell] could not record the install failure: ${err?.message || err}`);
  }
}

async function reportLastInstallFailure() {
  const file = installFailureFile();
  let record = null;
  try {
    record = JSON.parse(fs.readFileSync(file, "utf8"));
    fs.unlinkSync(file);
  } catch {
    return;
  }
  const logPath = safeLogPath();
  console.log(`[shell] the last update did not install (${record?.stage}): ${record?.message || "watchdog"}`);
  const { message, detail } = installFailureNotice({ ...record, logPath });
  const { response } = await messageBox({
    type: "warning",
    message,
    detail,
    buttons: ["Download latest release", "OK"],
    defaultId: 1,
    cancelId: 1,
  });
  if (response === 0) void shell.openExternal(RELEASES_URL);
}

function safeLogPath() {
  try {
    return log.transports.file.getFile().path;
  } catch {
    return "";
  }
}

function messageBox(options) {
  const parent = win && !win.isDestroyed() && win.isVisible() ? win : null;
  return parent ? dialog.showMessageBox(parent, options) : dialog.showMessageBox(options);
}

function buildMenu() {
  // Without an application menu, macOS loses Cmd+C/V/A entirely — the roles
  // below are what wire the system shortcuts, not decoration.
  const isMac = process.platform === "darwin";
  return Menu.buildFromTemplate([
    ...(isMac ? [{ role: "appMenu" }] : []),
    { role: "fileMenu" },
    { role: "editMenu" },
    {
      label: "View",
      submenu: [
        { label: "Reload app", accelerator: "CmdOrCtrl+R", click: () => appUrl && win?.loadURL(appUrl) },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" },
        {
          label: "Open in browser",
          click: () => appUrl && shell.openExternal(appUrl),
        },
        { type: "separator" },
        // Same item as the tray's, same function behind it. Here for the case
        // the tray cannot cover: no status area at all, where the window is by
        // definition the only surface there is.
        { ...trayUpdateItem(), click: () => void checkForUpdates(true) },
      ],
    },
    { role: "windowMenu" },
  ]);
}
